-- 001 — Sincroniza a tabela `imoveis` com o que o app grava.
-- Idempotente (ADD COLUMN IF NOT EXISTS). Aplicada automaticamente pelo Migrator.
ALTER TABLE imoveis
  ADD COLUMN IF NOT EXISTS link_maps        VARCHAR(800) NULL AFTER estado,
  ADD COLUMN IF NOT EXISTS link_street_view VARCHAR(800) NULL AFTER link_maps,
  ADD COLUMN IF NOT EXISTS numero_matricula VARCHAR(60)  NULL AFTER inscricao_municipal,
  ADD COLUMN IF NOT EXISTS cartorio         VARCHAR(180) NULL AFTER numero_matricula,
  ADD COLUMN IF NOT EXISTS comarca          VARCHAR(120) NULL AFTER site_cartorio,
  ADD COLUMN IF NOT EXISTS livro            VARCHAR(40)  NULL AFTER comarca,
  ADD COLUMN IF NOT EXISTS folha            VARCHAR(40)  NULL AFTER livro,
  ADD COLUMN IF NOT EXISTS data_matricula   DATE         NULL AFTER folha,
  ADD COLUMN IF NOT EXISTS percentual_participacao DECIMAL(5,2) NULL AFTER forma_aquisicao,
  ADD COLUMN IF NOT EXISTS area_privativa   DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS area_total       DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS area_construida  DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS area_comum       DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS area_terreno     DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS quartos          INT          NULL,
  ADD COLUMN IF NOT EXISTS suites           INT          NULL,
  ADD COLUMN IF NOT EXISTS banheiros        INT          NULL,
  ADD COLUMN IF NOT EXISTS lavabos          INT          NULL,
  ADD COLUMN IF NOT EXISTS vagas_garagem    INT          NULL,
  ADD COLUMN IF NOT EXISTS andar            INT          NULL,
  ADD COLUMN IF NOT EXISTS numero_unidade   VARCHAR(30)  NULL,
  ADD COLUMN IF NOT EXISTS face_solar       VARCHAR(30)  NULL,
  ADD COLUMN IF NOT EXISTS posicao_imovel   VARCHAR(60)  NULL,
  ADD COLUMN IF NOT EXISTS vista            VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS valor_contabil   DECIMAL(15,2) NULL AFTER data_avaliacao_mercado,
  ADD COLUMN IF NOT EXISTS empresa_avaliadora VARCHAR(180) NULL AFTER valor_contabil,
  ADD COLUMN IF NOT EXISTS valor_m2         DECIMAL(15,2) NULL AFTER empresa_avaliadora,
  ADD COLUMN IF NOT EXISTS custo_seguro     DECIMAL(10,2) NULL AFTER custo_internet;
